# Generated by Django 4.2.7 on 2023-11-27 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_docente', models.IntegerField()),
                ('apellido_docente', models.CharField(max_length=50)),
                ('nombre_docente', models.CharField(max_length=50)),
                ('telefono_docente', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_tutor', models.IntegerField()),
                ('apellido_tutor', models.CharField(max_length=50)),
                ('nombre_tutor', models.CharField(max_length=50)),
                ('telefono_tutor', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrio', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('vivienda', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('calle', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('casa', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('piso', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('depto', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('sector', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('dni_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=50)),
                ('anio_lectivo', models.PositiveIntegerField(default=2023, verbose_name='Año Lectivo')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.docente')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_alumno', models.IntegerField()),
                ('apellido_alumno', models.CharField(max_length=50)),
                ('nombre_alumno', models.CharField(max_length=50)),
                ('curso_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('docente_alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.docente')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutor')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
            },
        ),
    ]
