# Generated by Django 4.2.5 on 2023-11-06 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('dni_tutor', models.IntegerField(primary_key=True, serialize=False)),
                ('apellido_tutor', models.CharField(max_length=50)),
                ('nombre_tutor', models.CharField(max_length=50)),
                ('telefono_tutor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('dni_docente', models.IntegerField(primary_key=True, serialize=False)),
                ('apellido_docente', models.CharField(max_length=50)),
                ('nombre_docente', models.CharField(max_length=50)),
                ('telefono_docente', models.IntegerField()),
                ('curso_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('dni_alumno', models.IntegerField(primary_key=True, serialize=False)),
                ('apellido_alumno', models.CharField(max_length=50)),
                ('nombre_alumno', models.CharField(max_length=50)),
                ('curso_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('docente_alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.docente')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutor')),
            ],
        ),
    ]
