# Generated by Django 4.2.5 on 2023-11-08 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='curso_docente',
        ),
        migrations.AddField(
            model_name='curso',
            name='docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.docente'),
        ),
    ]
